name: data_analytics_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas=2.3.0
  - numpy=1.26.4
  - scipy=1.14.0
  - matplotlib=3.9.0
  - seaborn=0.13.2
  - scikit-learn=1.5.0
  - joblib=1.4.0
  - catboost=1.2.5
  - pyarrow=17.0.0
  - openpyxl=3.1.2
  - requests=2.32.0
  - notebook=7.2.0
  - ipython=8.26.0
  - jupyterlab=4.2.0
  - ipywidgets=8.1.2
  - jupyterlab-widgets=3.0.10
  - widgetsnbextension=4.0.10
  - jinja2=3.1.4
